### PR TITLE
point to latest templates head

### PR DESCRIPTION
**Pull request by djbe**

### CODE REVIEW

**Comment by djbe** [comment]
Hmmm, that isn't good 😕

**Comment by djbe** [comment]
Right, so what happened is:
- Add segue module info in swiftgenkit (deprecated vars PR)
- Added extra import tests in templates (missing ingore PR)

The latter added some info to templates but not everything, and this isn't tested in swiftgenkit until the next PR that updates the submodule.

**Comment by AliSoftware** [comment]
Should we do something to improve that, like see if we can trigger a submodule realignment + build in SwiftGenKit from templates PR or a warning via Danger if SwiftGenKit wasn't aligned before merging the PR or whatnot?

**Comment by djbe** [comment]
SwiftGenKit PRs should, before they get merged, have their submodules point to `master`. We could add a warning using Danger to check for this.

But it still won't help the issue that happened here, namely that a PR on templates was essentially broken but our tests didn't catch this, because these tests are run in the swiftgenkit repo. Somehow, template repo PRs that affect the fixtures, should run the tests in this repository...

**Comment by AliSoftware** [comment]
I have an idea but it can be complicated.

We could use `git-notes` inside `SwiftGenKit` to annotate the commits in `templates` to mark them as checked (unit tests passed). Then we could read those notes via Danger in `templates` PR so that a PR in `templates` checks if the latest commit has been checked by SwiftGenKit.

Not sure it's worth it. The best solution would rather be that the `templates` repo have a way to trigger a test action for the SwiftGenKit repo automatically, but I'm not sure that's possible. Maybe using a shared token and sending a URL call to a tailored WebHook? Invoking @dantoml on this…

**Comment by endocrimes** [comment]
@AliSoftware I need a little more context on this to be able to suggest something - We should definitely talk about it in Budapest this week tho.

**Comment by AliSoftware** [comment]
Yeah sure. 
So in a nutshell our "templates" repo is used to share fixtures used by unit tests in all our repos, like the "templates" repo itself but also this SwiftGenKit one.
So the question is, is it possible to either force running the SwiftGenKit's unit tests as part of a check for PRs in the "templates" repo (PR in templates => trigger SwiftGenKit's unit tests) or to use another mechanism (via Danger?) to make a templates PR fail if it hasn't been tested by a SwiftGenKit PR beforehand? 

We can talk more about it in Budapest next week indeed.

**Comment by djbe** [comment]
Right so SwiftGen works in 2 fases:
- Parse fixtures to generate contexts
- Render contexts to output files

We test those fases separately, the first fase is checked by the unit tests in `SwiftGenKit`, the second fase by the unit tests in the `templates` repository. 

The templates repository contains all the files (fixtures, contexts and expected output). The SwiftGenKit repository has the templates repository as a git submodule. All of this works, but an issue can arise in certain situations.

Edit: @AliSoftware beat me to it.

**Comment by djbe** [comment]
Thing is, if the templates repository could trigger a build in the SwiftGenKit repository, it'd have to trigger tests while making the latter point to the current `templates` branch. 

But then in some cases, we don't want that automation, because there might be a related PR in SwiftGenKit to handle the generation of modified contexts...

**Comment by djbe** [comment]
I think that the easiest would be:
- Danger on `templates` generates warnings (not errors) if the PR modifies fixtures or contexts.
- We can manually trigger a special build using @SwiftGen-DangerBot or something? (I've seen something like it in the Swift repositories, where they somehow trigger builds using github comments)

**Pull request merged**
