### PR TITLE
Fix swiftlint issues

### PR DESCRIPTION
**Pull request by Liquidsoul**
This fixes the swiftlint errors as states in #31

### CODE REVIEW

**Review by djbe — CHANGES_REQUESTED** [review]
Please add a changelog entry 😄

**Comment by Liquidsoul** [comment]
Oops sorry, forgot to do that 😅

**Review by djbe — APPROVED** [review]

**Comment by djbe** [comment]
The changelog entry'll need to be moved up to the new `master` section.

**Comment by Liquidsoul** [comment]
Done

**Pull request merged**
